### ISSUE TITLE
快捷键问题

### ISSUE THREAD

**Issue by sxzxs** [chriskyfung/Agile-Win-Hotkey-for-iFlyVoice#4]
能调用完后，把这个输入法退出吗
因为，快捷键讯飞自己也可以设置

**Comment by chriskyfung** [comment]
**To @sxzxs **:  不太明白你想問什麼。

---

### 附加說明

訊飛有快捷鍵的設置項，但是只得 <kbd>F2</kbd>、<kbd>F6</kbd> - <kbd>F10</kbd>功能鍵可供設置。
這些功能鍵在很多軟件中都是有用的，所以我才開發出這個外掛。

這個外掛可在不切換之訊飛輸入法時調用，不論你的Windows在當前的輸入法是英文(美國)的US鍵盤、繁體中文(香港)的微軟倉頡，或者日文的微軟輸入法，只要這個外掛已啟用，在工作列中顯示圖示，按下 <kbd>Win</kbd> + <kbd>H</kbd>即可在呼叫出訊飛輸入法的語音懸浮窗。再按 <kbd>Win</kbd> + <kbd>H</kbd> 即可結束語音輸入。

當語音懸浮窗最小化或被其他視窗遮蓋時，按 <kbd>Win</kbd> + <kbd>H</kbd> 會把懸浮窗拉回最上層顯示。

**Comment by sxzxs** [comment]
明白了，很实用
